language: java
jdk: oraclejdk7
env:
  global:
    - SDK_VERSION=r22.0.5
    - GRADLE_VERSION=1.6
    - BUILD_TOOLS_VERSION=18.0.1
    - ANDROID_GRADLE_VERSION=0.5.6
    - TESTFLIGHT_DISTIBUTION_LISTS=Public
    - secure: "Z7SgOOdYR0Cwj+LJ7Rnql/sD7Axfk9XU9p9aA86IbRzqQEks1mSYPeApb2UPOlzRVzKP1zpCSKLiMmlpZ/5MOc5DH6Bw9X195fyo8CW6airk5yz1n8R8v8Jn4uF8WkHx7wcebGuC1OSrn2a7clbns3FPEo6vrkMce02hqykFeJU="
    - secure: "W4WEghMQSVji4P3zKcnduNxSWRqo6RIs/W1t5VRKV1U9InK/79gVw7rG2ReyqTyjYsRBB6K1z3TRfwMVeRV7ImgWW82f7oDdufIVZBkDnwrRLtmti1hbtLI1zYnksBy57MJpHfTjMFStYMteid2+/NeyNS1I4Im7LEQHmHCopic="
    - secure: "Jss275/l7iBwlokfFBaoD30K6udVjWl7G7Zml3Wd1VNH7KV+IAc+UzNoHfDfYtjmiVga+Rg3/0YeMzfivXFHuUcwlOrSPOZhrH/wnKPhlZe614W4AYMM993DevMkPKHwZBnmNmUjjUEqxC/WWG8ahq0XNGLNcne3y8++Y+tAsU8="
    - secure: "KIAnEwBFbQG8p3FpJgHt2D1xEyLov/PdanYK9xHn5AZps2X327ypLJyoO6jTgwf7DnWcULiD0na9YwMBinYQsf5HiumLvxpsqo/yGHoYS2aPYzQvyfYkVMUIxdimeRDKV1KkRK4GzBwjiUg4oWpUiW818t0KWFoZoOW7NXUc3PU="
  matrix:
# Disabled emulator since we don't have tests at the moment
#    - ANDROID_VERSION=18  ANDROID_SDKS=android-18,sysimg-18  ANDROID_TARGET=android-18  ANDROID_ABI=armeabi-v7a
    - ANDROID_VERSION=18  ANDROID_SDKS=android-18

before_install:
  # Install base Android SDK
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
  - wget http://dl.google.com/android/android-sdk_${SDK_VERSION}-linux.tgz
  - tar xzf android-sdk_${SDK_VERSION}-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

  # Install required components.
  # For a full list, run `android list sdk -a --extended`
  # Note that sysimg-16 downloads the ARM, x86 and MIPS images (we should optimize this).
  # Note that `echo y` only accepts the first license. This is actually convenient, since
  # it prevents the installation of the ATOM and MIPS emulator images. It might cause
  # issues in the future though.
  - echo y | android update sdk --filter build-tools-${BUILD_TOOLS_VERSION},platform-tools,extra-android-support,extra-android-m2repository,${ANDROID_SDKS} --no-ui --force > /dev/null

# Disabled emulator since we on't have tests at the moment
#  # Create and start emulator
#  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
#  - emulator -avd test -no-skin -no-audio -no-window &
#  
#before_script:
#  - ./tools/wait_for_emulator

script:
  - export BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
  - gradle clean build

after_success:
  - ./tools/testflight

